# Generated by Django 4.0.1 on 2022-02-27 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtract', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_img',
        ),
    ]
