# Generated by Django 4.0.1 on 2022-02-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xtract', '0002_delete_post_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('pdf_file', models.FileField(upload_to='Images/', verbose_name='pdf_file')),
            ],
        ),
    ]
