# Generated by Django 4.0.1 on 2022-03-15 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtract', '0004_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
