# Generated by Django 4.0.1 on 2022-03-16 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtract', '0006_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='file3',
        ),
    ]
