# Generated by Django 4.0.1 on 2022-03-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtract', '0007_remove_photo_file1_remove_photo_file3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
