# Generated by Django 4.0.1 on 2022-03-16 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtract', '0009_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='file',
            new_name='file12',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='file2',
            new_name='file3',
        ),
    ]
