# Generated by Django 4.0.1 on 2022-03-16 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtract', '0010_rename_file_photo_file12_rename_file2_photo_file3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post_img',
        ),
    ]
